### PR TITLE
Include alpha version implementation

### LINKED ISSUE #1: augMENTOR alpha version repository
The task concerns the development of the repository for milestone M4 and D5.1

### PR DESCRIPTION
**Pull request by Alexa-Aposto**
Review augMENTOR alpha version

### CODE REVIEW

**Review by alimpertis — APPROVED** [review]
I've reviewed the changes proposed in this merge request and everything looks great!

**Review by dcharalampakis — APPROVED** [review]

**Review by EleftheriaTs — APPROVED** [review]
it's ok

**Comment by EleftheriaTs** [comment]
@Alexa-Aposto  in readme please replace 'teacher' with 'educator'.

**Comment by Alexa-Aposto** [comment]
> @Alexa-Aposto in readme please replace 'teacher' with 'educator'.

@EleftheriaTs This must remain as it is, since we follow the dictionary of  module.

**Pull request merged**
